Update Setup, Modifying Code and Testing sections.
supertokens/supertokens-python pull request #129
Opened 2022-04-26 05:07 UTC by sattvikc

## Summary of change

Updated Project Setup, Modifying Code and Testing sections in the CONTRIBUTING.md

## Related issues
None

## Test Plan
None

## Documentation changes
None

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
 
## Remaining TODOs for this PR
None

2022-04-26 18:55 UTC, rishabhpoddar requested changes

2022-04-26 18:55 UTC, rishabhpoddar commented on CONTRIBUTING.md
> +   `./startTestingEnv --wait`
Should be `./startTestEnv --wait`. The `startTestingEnv` script is deprecated.

2022-04-27 07:59 UTC, sattvikc commented on CONTRIBUTING.md
> +2. After modifying the code, test your changes by running `make test`
Removed.

2022-04-28 05:46 UTC, rishabhpoddar requested changes

2022-04-28 05:46 UTC, rishabhpoddar commented on CONTRIBUTING.md
> +   `cd ../supertokens-python`
```suggestion
```

2022-04-28 05:47 UTC, merged