refactor: Rename session_data related vars to clarify interaction with DB
supertokens/supertokens-python pull request #302
Opened 2023-03-30 13:14 UTC by KShivendu

## Summary of change

Rename sessionData related vars to clarity interaction with DB

## Related issues

-   https://github.com/supertokens/supertokens-node/pull/519

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py

2023-03-30 20:52 UTC, porcellus requested changes
Minor typo, otherwise LGTM.

2023-03-30 20:56 UTC, porcellus commented
There are a few comments in the examples that you may need to update; please check those as well.

2023-04-05 13:52 UTC, KShivendu commented on CHANGELOG.md
> +- Rename `get_session_data` to `get_session_data_from_database` to clarity that it always hits the DB
Done.

2023-04-05 23:09 UTC, porcellus approved these changes

2023-04-05 23:09 UTC, merged