feat: anti csrf made changed into a function
supertokens/supertokens-python pull request #327
Opened 2023-05-23 08:48 UTC by iresharma

## Summary of change

Convert `anti_csrf` into a function as part of app-info-refactor

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
 
## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-05-31 07:58 UTC, rishabhpoddar requested changes

2023-05-31 07:58 UTC, rishabhpoddar commented on supertokens_python/recipe/session/interfaces.py
> +        anti_csrf: str,
```suggestion
```

2023-05-31 07:58 UTC, rishabhpoddar commented on supertokens_python/recipe/session/interfaces.py
> +        anti_csrf: str,
```suggestion
```

2023-05-31 07:58 UTC, rishabhpoddar commented on supertokens_python/recipe/session/interfaces.py
> +        anti_csrf: str,
```suggestion
```

2023-06-01 11:41 UTC, nkshah2 requested changes

2023-06-01 11:41 UTC, nkshah2 commented on supertokens_python/recipe/session/syncio/__init__.py
> +    anti_csrf: Union[str, None] = None,
Is this required here? Its been removed from everywhere else

2023-06-01 11:41 UTC, nkshah2 commented on supertokens_python/recipe/session/session_request_functions.py
>      disable_anti_csrf = output_transfer_method == "header"
We should rename this to something more accurate

2023-06-01 11:41 UTC, nkshah2 commented on supertokens_python/recipe/session/asyncio/__init__.py
> +    anti_csrf: Union[str, None] = None,
This is not required

2023-06-01 11:41 UTC, nkshah2 commented on supertokens_python/recipe/session/recipe_implementation.py
> +            self, refresh_token, anti_csrf_token, disable_anti_csrf
Why did the formatting here change when the code hasnt?

2023-06-02 09:35 UTC, nkshah2 approved these changes

2023-06-02 09:35 UTC, nkshah2 approved these changes

2023-06-08 06:07 UTC, nkshah2 requested changes

2023-06-08 06:49 UTC, nkshah2 approved these changes

2023-06-08 07:28 UTC, merged