feat: email templates updated
supertokens/supertokens-python pull request #329
Opened 2023-05-24 08:36 UTC by iresharma

## Summary of change

(A few sentences about this PR)

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [xx] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [x] Had installed and ran the pre-commit hook
-   [x] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
 
## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-05-25 05:57 UTC, nkshah2 approved these changes

2023-05-25 05:57 UTC, nkshah2 commented on CHANGELOG.md
> +- Made changes to email templates to support superhuman
Refer to comment in node PR for the CHANGELOG copy

2023-05-25 05:57 UTC, nkshah2 requested changes

2023-05-25 05:57 UTC, nkshah2 commented on CHANGELOG.md
> +- Made changes to email templates to support superhuman
Refer to comment in node PR for the CHANGELOG copy

2023-05-31 04:57 UTC, nkshah2 approved these changes

2023-06-05 08:17 UTC, rishabhpoddar requested changes

2023-06-05 08:17 UTC, rishabhpoddar commented on setup.py
> +    version="0.14.2",
version update

2023-06-07 06:27 UTC, merged