App info refactor
supertokens/supertokens-python pull request #350
Opened 2023-06-16 07:30 UTC by iresharma

## Summary of change
This is python implementation of https://github.com/supertokens/supertokens-node/issues/342

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
 
## Remaining TODOs for this PR

-   [ ] apple_redirect_url -> figure out implementation
-   [ ] Write better messages for Exceptions
-   [ ] Rewrite changelog properly
-   [x] Change the funcs to take `BaseRequest | None`
-   [ ] CookieSameSite issue https://github.com/supertokens/supertokens-node/issues/506

2023-06-19 08:15 UTC, rishabhpoddar requested changes

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/utils.py
> +        return issuer_domain
need to normalise this?

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/utils.py
> +        issuer_domain_resp = await config.issuer_domain(None, user_context)  # type: ignore
do not use type ignore

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/syncio/__init__.py
> +    api_domain: Optional[str] = None,
why do you need both?

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/utils.py
>      issuer: Union[str, None] = None,
why is this not called issuer_domain?

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/interfaces.py
>          validity_seconds: Optional[int],
redo openid

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/asyncio/__init__.py
>      payload: Optional[Dict[str, Any]] = None,
redo openid recipe stuff

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/passwordless/asyncio/__init__.py
>  async def create_magic_link(
what about changes to syncio for this function of this recipe?

2023-06-19 08:15 UTC, rishabhpoddar commented on supertokens_python/recipe/thirdpartypasswordless/asyncio/__init__.py
>  async def create_magic_link(
what about changes to syncio for this recipe?

2023-06-19 08:21 UTC, iresharma commented on supertokens_python/supertokens.py
> +        await mutator(response=response)  # type: ignore
because all `mutator`s are now async

2023-06-20 06:14 UTC, rishabhpoddar requested changes

2023-06-20 06:14 UTC, rishabhpoddar commented on supertokens_python/recipe/jwt/utils.py
> +    issuer: Optional[str], app_info: AppInfo, user_context: Any
user_context should not be Any

2023-06-20 06:14 UTC, rishabhpoddar commented on supertokens_python/recipe/jwt/utils.py
> +    return issuer
normalise this

2023-06-20 06:14 UTC, rishabhpoddar commented on supertokens_python/recipe/jwt/utils.py
> +        )
get the request object from the user context and if it exists, call the function, else throw an error

2023-06-20 12:20 UTC, rishabhpoddar requested changes

2023-06-20 12:20 UTC, rishabhpoddar commented on supertokens_python/recipe/session/session_request_functions.py
> +        do_anti_csrf_check = False
```suggestion
```

2023-06-20 12:20 UTC, rishabhpoddar commented on supertokens_python/recipe/session/session_request_functions.py
> +            (disable_anti_csrf and config.anti_csrf == "VIA_TOKEN"),
why is this changed?

2023-06-20 12:20 UTC, rishabhpoddar commented on supertokens_python/recipe/session/syncio/__init__.py
> +    api_domain: Optional[str] = None,
call this issuer_domain

2023-06-20 12:56 UTC, iresharma commented on supertokens_python/recipe/openid/utils.py
> +        return issuer_domain_resp
this is similiar ro `initial_origin_string`

2023-06-21 08:24 UTC, rishabhpoddar requested changes

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/framework/django/django_middleware.py
> +            user_context = {}
create the default user context here - look at how it's done in APIs

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/framework/django/django_middleware.py
>              response = DjangoResponse(HttpResponse())
also pass in user_context in the manage_session_post_response function

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/cookie_and_header.py
> +    user_context: Dict[str, Any],
don't need user_context here, but as a part of the mutator function. And then the user_context will get passed into the mutator function in the manage_session_post_response

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/cookie_and_header.py
> +    user_context: Dict[str, Any],
no user_context here cause it will be in the mutator function

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/cookie_and_header.py
> +    user_context: Dict[str, Any],
no user_context required here

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/recipe.py
>              log_debug_message("errorHandler: returning INVALID_CLAIMS")
pass user_context to these other functions as well

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/utils.py
>              return api_domain_res.get_as_string_dangerous()
this type of change needs to be made everywhere.

2023-06-21 08:24 UTC, rishabhpoddar commented on supertokens_python/recipe/session/utils.py
>      if api_domain is None:
see if you can move this to the utils file in supertokens_python

2023-06-21 08:36 UTC, rishabhpoddar requested changes

2023-06-21 08:36 UTC, rishabhpoddar commented on supertokens_python/recipe/openid/utils.py
>      )
this whole thing can be moved into the normalised version of issuer_domain, and then you also don't need is_issuer_domain_given and initial_api_domain_type

2023-06-21 16:39 UTC, rishabhpoddar requested changes

2023-06-21 16:39 UTC, rishabhpoddar commented on supertokens_python/framework/django/django_middleware.py
didn't you also need to pass this to the middleware?

2023-06-22 07:07 UTC, rishabhpoddar requested changes

2023-06-22 07:07 UTC, rishabhpoddar commented on CHANGELOG.md
>  All notable changes to this project will be documented in this file.
add test which checks the number of occurances of `default_user_context(` function call

2024-07-29 07:21 UTC, closed without merging