fix: Emailverification send email functions with multitenancy
supertokens/supertokens-python pull request #383
Opened 2023-07-28 08:22 UTC by KShivendu

## Summary of change

Emailverification send email functions with multitenancy

## Related issues

-   https://github.com/supertokens/supertokens-node/pull/625

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [x] Make sure that `syncio` / `asyncio` functions are consistent.

2023-07-30 05:59 UTC, rishabhpoddar requested changes

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +    tenant_id: Optional[str],
set it to None by default

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +    tenant_id: Optional[str],
Set it to None by default

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +        tenant_id,
tenant_id should be part of template vars

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/syncio/__init__.py
> +    tenant_id: Optional[str],
set to none

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/syncio/__init__.py
> +    tenant_id: Optional[str],
set to none

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/dashboard/interfaces.py
> +
this error is not needed

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/interfaces.py
> +    status = "EMAIL_DOES_NOT_EXIST_ERROR"
this error is not needed

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +    SendEmailVerificationEmailDoesntExistError,
this error is not needed

2023-07-30 05:59 UTC, rishabhpoddar commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +            return SendEmailVerificationEmailDoesntExistError()
```suggestion
            return SendEmailVerificationEmailAlreadyVerifiedError()
```

2023-08-02 12:19 UTC, KShivendu commented on supertokens_python/recipe/dashboard/interfaces.py
> +
removed

2023-08-02 12:23 UTC, KShivendu commented on supertokens_python/recipe/emailverification/asyncio/__init__.py
> +    SendEmailVerificationEmailDoesntExistError,
Removed

2023-08-03 06:01 UTC, rishabhpoddar approved these changes

2023-08-03 08:58 UTC, merged