feat: Add dashboard admin feature
supertokens/supertokens-python pull request #442
Opened 2023-09-08 08:43 UTC by KShivendu

## Summary of change

Add dashboard admin feature

## Related issues

-   https://github.com/supertokens/supertokens-node/compare/15.1...feat/user-dashboard-user-permissions

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
-   [ ] If access token structure has changed
    -   Modified test in `tests/sessions/test_access_token_version.py` to account for any new claims that are optional or omitted by the core

2023-09-08 12:02 UTC, KShivendu commented
I manually tested the dashboard with admin by [temporarily hardcoding email header](https://github.com/supertokens/supertokens-python/pull/442/files#diff-f4df4bbc8354294e9aabe0f5501119a2e38cc6296adf7254dd0f015d235b8bb0R76) and setting admins config in dashboard recipe.

2023-09-12 08:03 UTC, rishabhpoddar requested changes

2023-09-12 08:03 UTC, rishabhpoddar commented on CHANGELOG.md
modify version

2023-09-12 08:03 UTC, rishabhpoddar commented on CHANGELOG.md
0.16.0 -> with the protected props thing for create new session.

2023-09-12 10:36 UTC, merged