feat: Use nest-asyncio when configured with env var
supertokens/supertokens-python pull request #451
Opened 2023-09-20 13:58 UTC by KShivendu

## Summary of change

Use nest-asyncio when configured with env var

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [x] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [x] Had installed and ran the pre-commit hook
-   [x] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
-   [ ] If access token structure has changed
    -   Modified test in `tests/sessions/test_access_token_version.py` to account for any new claims that are optional or omitted by the core

2023-09-20 13:59 UTC, KShivendu commented on CHANGELOG.md
> +- Allow use of [nest-asyncio](https://pypi.org/project/nest-asyncio/) when env var `SUPERTOKENS_NEST_ASYNCIO=1`.
Env var is better than changing the SDK interface. This is anyways a rare requirement and this way we can keep python SDK consistent with others.

2023-09-20 14:00 UTC, KShivendu commented on supertokens_python/utils.py
> -        loop.create_task(func())
This function wasn't used anywhere throughout the code. We discussed removing this last time.

2023-09-21 06:01 UTC, rishabhpoddar requested changes

2023-09-21 06:01 UTC, rishabhpoddar commented on supertokens_python/async_to_sync_wrapper.py
> +
make sure that there is at least one thing in cicd where we run the python sdk (for example in e2e test with flask), where nest_asyncio is not a dependency and then we make sure it all works

2023-09-21 10:54 UTC, rishabhpoddar commented on tests/test_config.py
> +            assert True
remove this

2023-09-21 11:09 UTC, KShivendu commented on tests/test_config.py
> +            assert True
Done

2023-09-21 11:16 UTC, merged