fix: [#474] return raw_user_info_from_provider in get_user_info in gi…
supertokens/supertokens-python pull request #553
Opened 2024-12-31 06:13 UTC by virajkanwade

…thub

## Summary of change

(A few sentences about this PR)

## Related issues

-   #474 

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens_python/constants.py`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `setup.py`
    -   In `supertokens_python/constants.py`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If have added a new web framework, update the `supertokens_python/utils.py` file to include that in the `FRAMEWORKS` variable
-   [ ] If added a new recipe that has a User type with extra info, then be sure to change the User type in supertokens_python/types.py
-   [ ] Make sure that `syncio` / `asyncio` functions are consistent.
-   [ ] If access token structure has changed
    -   Modified test in `tests/sessions/test_access_token_version.py` to account for any new claims that are optional or omitted by the core

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2024-12-31 06:14 UTC, virajkanwade commented
Couldn't get the tests to run on arm Mac. So making this into draft pull request. 
If someone could run the tests and verify, would be great.

2025-02-07 10:39 UTC, sattvikc requested changes

2025-02-07 10:39 UTC, sattvikc commented on supertokens_python/recipe/thirdparty/providers/github.py
>          for info in email_info:
Changes look fine to me. please update changelog and version.

2025-02-07 14:06 UTC, mavwolverine commented on supertokens_python/recipe/thirdparty/providers/github.py
>          for info in email_info:
changelog updated

2025-02-10 07:42 UTC, closed without merging

2025-02-10 07:42 UTC, namsnath commented
Hi @mavwolverine,
I'm closing this PR out in favor of #558.
Added some additional changes there on top of the ones you suggested here, and added you as a co-author.

Thanks a lot for the contribution!